defaults:
  - model_checkpoint.yaml

model_checkpoint:
  dirpath: ~  # ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/acc"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
